#import "MusicPlayer.h"
#import "ResearchUI.h"
#import "MusicAPI.h"
#import <CoreImage/CoreImage.h>
@interface TMMusicPanel:UITableViewController<UISearchBarDelegate>
@property UIImageView *art;
@property UISegmentedControl *pageMode;
@property UIStackView *playerStack,*discoveryStack;
@property BOOL showDisplaySettings;
@property UILabel *songLabel,*artistLabel,*stateLabel,*lyricLabel,*bridgeLabel,*timeLabel;
@property UIButton *playButton,*loginButton;
@property UISlider *progress;
@property UISegmentedControl *displayMode;
@property UISwitch *glassesSwitch;
@property NSArray *results;
@property NSTimer *refreshTimer;
@property NSUInteger searchTicket;
@property UIImage *lastCover;
@end
@interface TMLoginPanel:UIViewController
@property UIImageView *qr;
@property UILabel *note;
@property NSTimer *timer;
@property NSString *key;
@property NSDate *expiry;
@property BOOL checking;
@end
@implementation TMLoginPanel
- (void)viewDidLoad{[super viewDidLoad];self.title=@"网易云登录";self.view.backgroundColor=UIColor.systemBackgroundColor;_qr=[UIImageView new];_qr.contentMode=UIViewContentModeScaleAspectFit;_note=[UILabel new];_note.numberOfLines=0;_note.textAlignment=NSTextAlignmentCenter;_note.text=@"正在获取二维码…\n请用网易云 App 扫码并确认。登录态仅保存在本机钥匙串。";
 UIStackView *stack=[[UIStackView alloc]initWithArrangedSubviews:@[_qr,_note]];stack.axis=UILayoutConstraintAxisVertical;stack.spacing=24;stack.translatesAutoresizingMaskIntoConstraints=NO;[self.view addSubview:stack];[NSLayoutConstraint activateConstraints:@[[stack.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor constant:28],[stack.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor constant:-28],[stack.topAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.topAnchor constant:36],[_qr.heightAnchor constraintEqualToConstant:280]]];
 __weak typeof(self) weak=self;[[TMMusicAPI shared]request:@"/api/login/qrcode/unikey" payload:@{@"type":@3} eapi:YES done:^(NSDictionary *j,NSString *error){TMLoginPanel *s=weak;if(!s)return;id key=j[@"unikey"];if(![key isKindOfClass:NSString.class]&&[j[@"data"]isKindOfClass:NSDictionary.class])key=j[@"data"][@"unikey"];if(error||![key isKindOfClass:NSString.class]){s.note.text=error?:@"二维码获取失败，返回重试";return;}s.key=key;s.expiry=[NSDate dateWithTimeIntervalSinceNow:120];NSString *url=[@"https://music.163.com/login?codekey=" stringByAppendingString:[key stringByAddingPercentEncodingWithAllowedCharacters:NSCharacterSet.URLQueryAllowedCharacterSet]];CIFilter *f=[CIFilter filterWithName:@"CIQRCodeGenerator"];[f setValue:[url dataUsingEncoding:NSUTF8StringEncoding] forKey:@"inputMessage"];CIImage *image=[f.outputImage imageByApplyingTransform:CGAffineTransformMakeScale(8,8)];CGImageRef cg=[[CIContext contextWithOptions:nil]createCGImage:image fromRect:image.extent];if(cg){s.qr.image=[UIImage imageWithCGImage:cg];CGImageRelease(cg);}s.note.text=@"请用网易云音乐扫码确认\n二维码两分钟有效；不会读取你的密码。";s.timer=[NSTimer scheduledTimerWithTimeInterval:3 repeats:YES block:^(NSTimer *t){[weak check];}];}];
}
- (void)check{if(_checking)return;if([_expiry timeIntervalSinceNow]<=0){[_timer invalidate];_note.text=@"二维码过期，请返回重试";return;}_checking=YES;__weak typeof(self) weak=self;[[TMMusicAPI shared]request:@"/api/login/qrcode/client/login" payload:@{@"key":_key,@"type":@3} eapi:YES done:^(NSDictionary *j,NSString *error){TMLoginPanel *s=weak;if(!s)return;s.checking=NO;NSInteger code=[j[@"code"]integerValue];if(code==803){[s.timer invalidate];s.note.text=TMMusicAPI.shared.hasLogin?@"已登录，返回音乐页即可使用":@"已确认，但未保存登录态，请重试";}else if(code==800){[s.timer invalidate];s.note.text=@"二维码已过期";}else if(code==802)s.note.text=@"已扫码，请在网易云确认";else if(error)s.note.text=error;}];}
- (void)viewDidDisappear:(BOOL)animated{[super viewDidDisappear:animated];[_timer invalidate];_timer=nil;}
@end
static UILabel *Label(CGFloat size,UIFontWeight weight){UILabel *l=[UILabel new];l.font=[[UIFontMetrics metricsForTextStyle:UIFontTextStyleBody] scaledFontForFont:[UIFont systemFontOfSize:size weight:weight]];l.adjustsFontForContentSizeCategory=YES;l.textColor=UIColor.labelColor;l.numberOfLines=0;return l;}
static UIButton *Button(NSString *title,NSString *symbol,id target,SEL action){UIButton *b=[UIButton buttonWithType:UIButtonTypeSystem];UIButtonConfiguration *c=[UIButtonConfiguration plainButtonConfiguration];c.title=title;c.image=symbol?[UIImage systemImageNamed:symbol]:nil;c.baseForegroundColor=TIOInk();c.preferredSymbolConfigurationForImage=[UIImageSymbolConfiguration configurationWithPointSize:23 weight:UIImageSymbolWeightMedium];c.imagePadding=8;b.configuration=c;[b addTarget:target action:action forControlEvents:UIControlEventTouchUpInside];return b;}
static UIView *Inset(UIStackView *stack,CGFloat inset,UIColor *color){UIView *v=[UIView new];v.backgroundColor=color;v.layer.cornerRadius=22;v.layer.cornerCurve=kCACornerCurveContinuous;stack.translatesAutoresizingMaskIntoConstraints=NO;[v addSubview:stack];[NSLayoutConstraint activateConstraints:@[[stack.leadingAnchor constraintEqualToAnchor:v.leadingAnchor constant:inset],[stack.trailingAnchor constraintEqualToAnchor:v.trailingAnchor constant:-inset],[stack.topAnchor constraintEqualToAnchor:v.topAnchor constant:inset],[stack.bottomAnchor constraintEqualToAnchor:v.bottomAnchor constant:-inset]]];return v;}
static UIImage *IdleCover(void){UIGraphicsImageRendererFormat *f=[UIGraphicsImageRendererFormat defaultFormat];f.scale=1;return [[[UIGraphicsImageRenderer alloc]initWithSize:CGSizeMake(320,320) format:f]imageWithActions:^(UIGraphicsImageRendererContext *r){CGContextRef c=r.CGContext;CGColorSpaceRef cs=CGColorSpaceCreateDeviceRGB();CGFloat colors[]={.22,.15,.12,1,.065,.055,.055,1};CGGradientRef g=CGGradientCreateWithColorComponents(cs,colors,NULL,2);CGContextDrawLinearGradient(c,g,CGPointZero,CGPointMake(320,320),0);CGGradientRelease(g);CGColorSpaceRelease(cs);for(int i=0;i<8;i++){[[UIColor colorWithWhite:.85 alpha:.035]setStroke];UIBezierPath *p=[UIBezierPath bezierPathWithOvalInRect:CGRectMake(34+i*8,34+i*8,252-i*16,252-i*16)];p.lineWidth=1;[p stroke];}UIImage *note=[UIImage systemImageNamed:@"music.note" withConfiguration:[UIImageSymbolConfiguration configurationWithPointSize:64 weight:UIImageSymbolWeightLight]];[[note imageWithTintColor:[UIColor colorWithRed:.96 green:.7 blue:.49 alpha:1] renderingMode:UIImageRenderingModeAlwaysOriginal]drawInRect:CGRectMake(130,120,60,76)];[@"T U R B O   I O" drawAtPoint:CGPointMake(96,276) withAttributes:@{NSFontAttributeName:[UIFont systemFontOfSize:13 weight:UIFontWeightMedium],NSForegroundColorAttributeName:[UIColor colorWithWhite:.65 alpha:1]}];}];}
@implementation TMMusicPanel
- (void)viewDidLoad{[super viewDidLoad];self.title=@"网易云音乐";self.hidesBottomBarWhenPushed=YES;self.overrideUserInterfaceStyle=UIUserInterfaceStyleDark;self.tableView.backgroundColor=TIOPaper();self.tableView.separatorStyle=UITableViewCellSeparatorStyleNone;self.tableView.tintColor=TIOAccent();
 UINavigationBarAppearance *appearance=[UINavigationBarAppearance new];[appearance configureWithDefaultBackground];appearance.backgroundColor=[TIOPaper()colorWithAlphaComponent:.25];appearance.shadowColor=UIColor.clearColor;appearance.titleTextAttributes=@{NSForegroundColorAttributeName:TIOInk(),NSFontAttributeName:[UIFont systemFontOfSize:17 weight:UIFontWeightSemibold]};self.navigationItem.standardAppearance=appearance;self.navigationItem.scrollEdgeAppearance=appearance;self.navigationItem.compactAppearance=appearance;
 UIBarButtonItem *more=[[UIBarButtonItem alloc]initWithImage:[UIImage systemImageNamed:@"ellipsis.circle"] style:UIBarButtonItemStylePlain target:self action:@selector(more)],*account=[[UIBarButtonItem alloc]initWithImage:[UIImage systemImageNamed:@"person.crop.circle"] style:UIBarButtonItemStylePlain target:self action:@selector(login)];more.tintColor=account.tintColor=TIOInk();more.accessibilityLabel=@"音乐菜单";account.accessibilityLabel=@"网易云账号";self.navigationItem.rightBarButtonItems=@[more,account];
 UISearchBar *search=[UISearchBar new];search.placeholder=@"搜索你想听的音乐";search.delegate=self;search.searchBarStyle=UISearchBarStyleMinimal;search.searchTextField.font=[UIFont systemFontOfSize:14];self.tableView.keyboardDismissMode=UIScrollViewKeyboardDismissModeOnDrag;
 UILabel *eyebrow=Label(10,UIFontWeightSemibold);eyebrow.text=@"T U R B O  I O   /   M U S I C";eyebrow.textColor=UIColor.secondaryLabelColor;eyebrow.textAlignment=NSTextAlignmentCenter;
 _art=[UIImageView new];_art.contentMode=UIViewContentModeScaleAspectFill;_art.clipsToBounds=YES;_art.layer.cornerRadius=16;_art.layer.cornerCurve=kCACornerCurveContinuous;_art.image=TIOArtwork(@"music")?:IdleCover();_art.translatesAutoresizingMaskIntoConstraints=NO;UIView *artWrap=[UIView new];[artWrap addSubview:_art];[NSLayoutConstraint activateConstraints:@[[_art.centerXAnchor constraintEqualToAnchor:artWrap.centerXAnchor],[_art.topAnchor constraintEqualToAnchor:artWrap.topAnchor constant:4],[_art.bottomAnchor constraintEqualToAnchor:artWrap.bottomAnchor constant:-4],[_art.widthAnchor constraintEqualToAnchor:_art.heightAnchor],[_art.heightAnchor constraintEqualToConstant:232]]];
 _songLabel=Label(24,UIFontWeightMedium);_songLabel.numberOfLines=1;_songLabel.lineBreakMode=NSLineBreakByTruncatingTail;_artistLabel=Label(14,UIFontWeightRegular);_artistLabel.textColor=UIColor.secondaryLabelColor;_artistLabel.numberOfLines=1;UIStackView *metadata=[[UIStackView alloc]initWithArrangedSubviews:@[_songLabel,_artistLabel]];metadata.axis=UILayoutConstraintAxisVertical;metadata.spacing=5;
 _stateLabel=Label(11,UIFontWeightRegular);_stateLabel.textColor=UIColor.secondaryLabelColor;_stateLabel.hidden=YES;_timeLabel=Label(11,UIFontWeightRegular);_timeLabel.font=[UIFont monospacedDigitSystemFontOfSize:11 weight:UIFontWeightRegular];_timeLabel.textColor=UIColor.secondaryLabelColor;_timeLabel.textAlignment=NSTextAlignmentCenter;
 _lyricLabel=Label(17,UIFontWeightMedium);_lyricLabel.textColor=TIOAccent();_lyricLabel.textAlignment=NSTextAlignmentCenter;_lyricLabel.numberOfLines=3;[_lyricLabel.heightAnchor constraintGreaterThanOrEqualToConstant:76].active=YES;
 _bridgeLabel=Label(11,UIFontWeightRegular);_bridgeLabel.textColor=UIColor.secondaryLabelColor;_bridgeLabel.numberOfLines=2;
 _progress=[UISlider new];_progress.minimumTrackTintColor=TIOAccent();_progress.maximumTrackTintColor=UIColor.separatorColor;UIGraphicsImageRenderer *thumb=[[UIGraphicsImageRenderer alloc]initWithSize:CGSizeMake(10,10)];UIImage *dot=[thumb imageWithActions:^(UIGraphicsImageRendererContext *r){[UIColor.whiteColor setFill];[[UIBezierPath bezierPathWithOvalInRect:CGRectMake(0,0,10,10)]fill];}];[_progress setThumbImage:dot forState:UIControlStateNormal];[_progress addTarget:self action:@selector(seek) forControlEvents:UIControlEventTouchUpInside|UIControlEventTouchUpOutside];UIStackView *timeline=[[UIStackView alloc]initWithArrangedSubviews:@[_progress,_timeLabel]];timeline.axis=UILayoutConstraintAxisVertical;timeline.spacing=-4;
 _playButton=Button(@"",@"play.fill",self,@selector(toggle));UIButtonConfiguration *play=_playButton.configuration;play.baseForegroundColor=TIOPaper();play.background.backgroundColor=TIOAccent();play.background.cornerRadius=32;_playButton.configuration=play;_playButton.accessibilityLabel=@"播放 / 暂停";
 UIButton *previous=Button(@"",@"backward.end.fill",self,@selector(previous)),*next=Button(@"",@"forward.end.fill",self,@selector(next));previous.accessibilityLabel=@"上一首";next.accessibilityLabel=@"下一首";UIStackView *controls=[[UIStackView alloc]initWithArrangedSubviews:@[previous,_playButton,next]];controls.alignment=UIStackViewAlignmentCenter;controls.distribution=UIStackViewDistributionEqualSpacing;UIView *controlWrap=Inset(controls,8,nil);[_playButton.widthAnchor constraintEqualToConstant:64].active=YES;[_playButton.heightAnchor constraintEqualToConstant:64].active=YES;[previous.widthAnchor constraintEqualToConstant:64].active=YES;[next.widthAnchor constraintEqualToConstant:64].active=YES;
 _glassesSwitch=[UISwitch new];_glassesSwitch.on=TMPlayer.shared.glasses;_glassesSwitch.onTintColor=TIOAccent();[_glassesSwitch addTarget:self action:@selector(glassesChanged) forControlEvents:UIControlEventValueChanged];UILabel *caption=Label(15,UIFontWeightSemibold);caption.text=@"眼镜显示";UIImageView *glass=[[UIImageView alloc]initWithImage:[UIImage systemImageNamed:@"eyeglasses"]];glass.tintColor=TIOInk();glass.contentMode=UIViewContentModeScaleAspectFit;[glass.widthAnchor constraintEqualToConstant:24].active=YES;UIStackView *switchRow=[[UIStackView alloc]initWithArrangedSubviews:@[glass,caption,_glassesSwitch]];switchRow.alignment=UIStackViewAlignmentCenter;switchRow.spacing=10;
 _displayMode=[[UISegmentedControl alloc]initWithItems:@[@"常亮",@"30 秒",@"1 分钟"]];_displayMode.selectedSegmentIndex=TMPlayer.shared.mode;_displayMode.backgroundColor=UIColor.tertiarySystemFillColor;_displayMode.selectedSegmentTintColor=UIColor.secondarySystemGroupedBackgroundColor;[_displayMode addTarget:self action:@selector(modeChanged) forControlEvents:UIControlEventValueChanged];UIButton *durationButton=Button(@"显示时长",@"chevron.down",self,@selector(toggleDisplaySettings));durationButton.contentHorizontalAlignment=UIControlContentHorizontalAlignmentLeading;_displayMode.hidden=YES;
 UIStackView *cardStack=[[UIStackView alloc]initWithArrangedSubviews:@[switchRow,durationButton,_displayMode,_bridgeLabel]];cardStack.axis=UILayoutConstraintAxisVertical;cardStack.spacing=12;UIView *card=Inset(cardStack,16,UIColor.secondarySystemGroupedBackgroundColor);
 _pageMode=[[UISegmentedControl alloc]initWithItems:@[@"正在播放",@"发现音乐"]];_pageMode.selectedSegmentIndex=0;[_pageMode addTarget:self action:@selector(pageModeChanged) forControlEvents:UIControlEventValueChanged];_pageMode.accessibilityIdentifier=@"music-page-mode";
 _playerStack=[[UIStackView alloc]initWithArrangedSubviews:@[artWrap,metadata,_lyricLabel,timeline,controlWrap,card,_stateLabel]];_playerStack.axis=UILayoutConstraintAxisVertical;_playerStack.spacing=14;
 UILabel *searchNote=Label(14,UIFontWeightRegular);searchNote.text=@"搜索歌曲，或从右上角菜单打开歌单。\n无需登录也可以尝试有权播放的内容。";searchNote.textColor=UIColor.secondaryLabelColor;
 _discoveryStack=[[UIStackView alloc]initWithArrangedSubviews:@[search,searchNote]];_discoveryStack.axis=UILayoutConstraintAxisVertical;_discoveryStack.spacing=16;_discoveryStack.hidden=YES;
 UIStackView *stack=[[UIStackView alloc]initWithArrangedSubviews:@[_pageMode,_playerStack,_discoveryStack]];stack.axis=UILayoutConstraintAxisVertical;stack.spacing=22;stack.translatesAutoresizingMaskIntoConstraints=NO;UIView *header=[UIView new];[header addSubview:stack];[NSLayoutConstraint activateConstraints:@[[stack.leadingAnchor constraintEqualToAnchor:header.leadingAnchor constant:26],[stack.trailingAnchor constraintEqualToAnchor:header.trailingAnchor constant:-26],[stack.topAnchor constraintEqualToAnchor:header.topAnchor constant:0],[stack.bottomAnchor constraintEqualToAnchor:header.bottomAnchor constant:-26]]];self.tableView.tableHeaderView=header;NSArray *saved=nil;{id raw=[NSUserDefaults.standardUserDefaults objectForKey:@"TurboMusicPlaylistV1"];if([raw isKindOfClass:NSData.class])saved=[NSJSONSerialization JSONObjectWithData:raw options:0 error:nil];if([saved isKindOfClass:NSArray.class]&&saved.count){_results=[saved mutableCopy];_pageMode.selectedSegmentIndex=1;[self pageModeChanged];}}[self refresh];
}
- (void)viewDidLayoutSubviews{[super viewDidLayoutSubviews];UIView *h=self.tableView.tableHeaderView;CGFloat width=self.tableView.bounds.size.width;CGSize s=[h systemLayoutSizeFittingSize:CGSizeMake(width,0) withHorizontalFittingPriority:UILayoutPriorityRequired verticalFittingPriority:UILayoutPriorityFittingSizeLevel];if(fabs(h.frame.size.height-s.height)>1||h.frame.size.width!=width){h.frame=CGRectMake(0,0,width,s.height);self.tableView.tableHeaderView=h;}}
- (void)viewWillAppear:(BOOL)animated{[super viewWillAppear:animated];__weak typeof(self) weak=self;_refreshTimer=[NSTimer scheduledTimerWithTimeInterval:.4 repeats:YES block:^(NSTimer *t){[weak refresh];}];}
- (void)viewDidDisappear:(BOOL)animated{[super viewDidDisappear:animated];[_refreshTimer invalidate];_refreshTimer=nil;}
- (void)refresh{TMPlayer *p=TMPlayer.shared;_songLabel.text=p.song[@"name"]?:@"随音乐，看见歌词";_artistLabel.text=p.song[@"artist"]?:@"选择一首歌，开始你的音乐旅程";if(_lastCover!=p.cover){_lastCover=p.cover;_art.image=p.cover?:TIOArtwork(@"music")?:IdleCover();}_stateLabel.text=p.status;BOOL steady=[p.status isEqual:@"播放中"]||[p.status isEqual:@"已暂停"]||!p.song;_stateLabel.hidden=steady;_bridgeLabel.text=p.glasses?p.bridgeStatus:@"将封面与歌词同步到眼镜，需要音乐版固件。";_glassesSwitch.on=p.glasses;_displayMode.enabled=p.glasses;_displayMode.alpha=p.glasses?1:.5;_timeLabel.text=[NSString stringWithFormat:@"%02ld:%02ld  /  %02ld:%02ld",(long)p.position/60,(long)p.position%60,(long)p.duration/60,(long)p.duration%60];if(!_progress.tracking){_progress.maximumValue=MAX(1,p.duration);_progress.value=p.position;}UIButtonConfiguration *c=_playButton.configuration;c.title=@"";c.image=[UIImage systemImageNamed:p.playing?@"pause.fill":@"play.fill"];_playButton.configuration=c;_playButton.accessibilityLabel=p.playing?@"暂停":@"播放";NSString *line=p.song?@"让旋律慢慢流淌":@"你的下一段旋律，在这里";NSInteger current=-1;for(NSUInteger i=0;i<p.lyrics.count;i++){if([p.lyrics[i][@"ms"]doubleValue]>p.position*1000)break;current=i;}if(current>=0){NSMutableAttributedString *text=[NSMutableAttributedString new];for(NSInteger i=MAX(0,current-1);i<MIN((NSInteger)p.lyrics.count,current+2);i++){if(text.length)[text appendAttributedString:[[NSAttributedString alloc]initWithString:@"\n"]];NSDictionary *attrs=@{NSForegroundColorAttributeName:i==current?TIOInk():UIColor.secondaryLabelColor,NSFontAttributeName:[UIFont systemFontOfSize:i==current?17:14 weight:i==current?UIFontWeightMedium:UIFontWeightRegular]};[text appendAttributedString:[[NSAttributedString alloc]initWithString:p.lyrics[i][@"text"]?:@"" attributes:attrs]];}_lyricLabel.attributedText=text;}else if(![_lyricLabel.text isEqual:line]){_lyricLabel.text=line;}[self.view setNeedsLayout];}
- (void)pageModeChanged{_playerStack.hidden=_pageMode.selectedSegmentIndex==1;_discoveryStack.hidden=!_playerStack.hidden;[self.tableView reloadData];[self.view setNeedsLayout];}
- (void)toggleDisplaySettings{_showDisplaySettings=!_showDisplaySettings;_displayMode.hidden=!_showDisplaySettings;[self.view setNeedsLayout];}
- (void)more{UIAlertController *a=[UIAlertController alertControllerWithTitle:@"音乐" message:nil preferredStyle:UIAlertControllerStyleActionSheet];__weak typeof(self) weak=self;[a addAction:[UIAlertAction actionWithTitle:@"打开网易云歌单" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){[weak playlist];}]];[a addAction:[UIAlertAction actionWithTitle:@"打开听书（电台 ID）" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){[weak djPlaylist];}]];[a addAction:[UIAlertAction actionWithTitle:@"显示到眼镜" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){[weak showGlasses];}]];[a addAction:[UIAlertAction actionWithTitle:@"关闭眼镜画面" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){[weak hideGlasses];}]];[a addAction:[UIAlertAction actionWithTitle:@"播放本机校验曲" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){[weak demo];}]];[a addAction:[UIAlertAction actionWithTitle:@"连接与播放状态" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){TMMusicPanel *s=weak;if(!s)return;UIAlertController *d=[UIAlertController alertControllerWithTitle:@"播放诊断" message:[NSString stringWithFormat:@"%@\n\n%@",TMPlayer.shared.status,TMPlayer.shared.bridgeStatus] preferredStyle:UIAlertControllerStyleAlert];[d addAction:[UIAlertAction actionWithTitle:@"完成" style:UIAlertActionStyleCancel handler:nil]];[s presentViewController:d animated:YES completion:nil];}]];[a addAction:[UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"粘贴 Cookie 登录（试验）" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){TMMusicPanel *s=weak;if(!s)return;UIAlertController *c=[UIAlertController alertControllerWithTitle:@"粘贴 Cookie 登录" message:@"从网易云网页版登录后，复制 Cookie 里的 MUSIC_U=...; NMTID=...（可整段粘贴）。导入后试播验证；仍可能被风控。" preferredStyle:UIAlertControllerStyleAlert];[c addTextFieldWithConfigurationHandler:^(UITextField *f){f.placeholder=@"MUSIC_U=...; NMTID=...";f.keyboardType=UIKeyboardTypeASCIICapable;}];[c addAction:[UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStyleCancel handler:nil]];[c addAction:[UIAlertAction actionWithTitle:@"导入" style:UIAlertActionStyleDefault handler:^(UIAlertAction *y){UITextField *t=c.textFields.firstObject;BOOL ok=[TMMusicAPI.shared importCookieString:t.text];UIAlertController *d=[UIAlertController alertControllerWithTitle:ok?@"已导入，去试播验证":@"导入失败" message:ok?@"请在播放页选歌验证。仍显示试听说明 Cookie 被风控（无解）。":@"请确认复制了 MUSIC_U=... 格式" preferredStyle:UIAlertControllerStyleAlert];[d addAction:[UIAlertAction actionWithTitle:@"好" style:UIAlertActionStyleCancel handler:nil]];[s presentViewController:d animated:YES completion:nil];[s refresh];}]];[s presentViewController:c animated:YES completion:nil];}]];a.popoverPresentationController.barButtonItem=self.navigationItem.rightBarButtonItems.firstObject;[self presentViewController:a animated:YES completion:nil];}
- (void)toggle{[TMPlayer.shared play:!TMPlayer.shared.playing];}- (void)previous{[TMPlayer.shared step:-1];}- (void)next{[TMPlayer.shared step:1];}- (void)seek{[TMPlayer.shared seek:_progress.value];}- (void)demo{[TMPlayer.shared demo];}- (void)modeChanged{TMPlayer.shared.mode=_displayMode.selectedSegmentIndex;}- (void)glassesChanged{TMPlayer.shared.glasses=_glassesSwitch.on;}- (void)showGlasses{[TMPlayer.shared showOnGlasses];}- (void)hideGlasses{[TMPlayer.shared hideGlasses];}
- (void)login{if(!TMMusicAPI.shared.hasLogin){[self.navigationController pushViewController:[TMLoginPanel new] animated:YES];return;}UIAlertController *a=[UIAlertController alertControllerWithTitle:@"网易云账号" message:@"已登录，凭据仅保存在本机钥匙串。不使用已有独立网易云 App 的登录状态。" preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"关闭" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"退出账号" style:UIAlertActionStyleDestructive handler:^(UIAlertAction *x){[TMPlayer.shared play:NO];[TMMusicAPI.shared logout];[self refresh];}]];[self presentViewController:a animated:YES completion:nil];}
- (void)playlist{UIAlertController *a=[UIAlertController alertControllerWithTitle:@"打开网易云歌单" message:@"输入歌单 ID（分享链接中的 id）。当前账号无权访问的内容不会绕过限制。" preferredStyle:UIAlertControllerStyleAlert];[a addTextFieldWithConfigurationHandler:^(UITextField *f){f.placeholder=@"歌单 ID";f.keyboardType=UIKeyboardTypeNumberPad;}];[a addAction:[UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"打开" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){long long n=a.textFields.firstObject.text.longLongValue;if(n<=0)return;[self load:@"/api/v6/playlist/detail" payload:@{@"id":@(n),@"n":@1000,@"s":@8} eapi:YES];}]];[self presentViewController:a animated:YES completion:nil];}
- (void)djPlaylist{UIAlertController *a=[UIAlertController alertControllerWithTitle:@"打开听书/电台" message:@"输入网易云电台（有声书专辑）ID。每集按 mainSong 播放，眼镜显示节目名。" preferredStyle:UIAlertControllerStyleAlert];[a addTextFieldWithConfigurationHandler:^(UITextField *f){f.placeholder=@"电台 ID";f.keyboardType=UIKeyboardTypeNumberPad;}];[a addAction:[UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"打开" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){long long n=a.textFields.firstObject.text.longLongValue;if(n<=0)return;[self loadDj:@{@"radioId":@(n),@"limit":@1000,@"offset":@0}];}]];[self presentViewController:a animated:YES completion:nil];}
- (void)searchBarSearchButtonClicked:(UISearchBar *)searchBar{[searchBar resignFirstResponder];NSString *s=[searchBar.text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];if(s.length)[self load:@"/api/cloudsearch/pc" payload:@{@"s":s,@"type":@1,@"limit":@30,@"offset":@0,@"total":@YES} eapi:NO];}
- (void)load:(NSString *)path payload:(NSDictionary *)payload eapi:(BOOL)eapi{NSUInteger ticket=++_searchTicket;self.navigationItem.prompt=@"正在加载…";__weak typeof(self) weak=self;[TMMusicAPI.shared request:path payload:payload eapi:eapi done:^(NSDictionary *j,NSString *err){TMMusicPanel *s=weak;if(!s||s.searchTicket!=ticket)return;id parent=j[eapi?@"playlist":@"result"];id list=[parent isKindOfClass:NSDictionary.class]?parent[eapi?@"tracks":@"songs"]:nil;NSMutableArray *valid=[NSMutableArray new];if([list isKindOfClass:NSArray.class])for(id row in list)if([row isKindOfClass:NSDictionary.class])[valid addObject:row];s.results=valid;{NSData *plData=[NSJSONSerialization dataWithJSONObject:valid options:0 error:nil];if(plData)[NSUserDefaults.standardUserDefaults setObject:plData forKey:@"TurboMusicPlaylistV1"];}s.pageMode.selectedSegmentIndex=1;[s pageModeChanged];s.navigationItem.prompt=err?:[NSString stringWithFormat:@"%lu 首 · 向下选择歌曲",(unsigned long)s.results.count];[s.tableView reloadData];if(s.results.count)[s.tableView scrollToRowAtIndexPath:[NSIndexPath indexPathForRow:0 inSection:0]atScrollPosition:UITableViewScrollPositionTop animated:YES];}];}
- (void)loadDj:(NSDictionary *)payload{NSUInteger ticket=++_searchTicket;self.navigationItem.prompt=@"正在加载…";__weak typeof(self) weak=self;[TMMusicAPI.shared request:@"/api/dj/program/byradio" payload:payload eapi:YES done:^(NSDictionary *j,NSString *err){TMMusicPanel *s=weak;if(!s||s.searchTicket!=ticket)return;id list=[j[@"programs"]isKindOfClass:NSArray.class]?j[@"programs"]:@[];NSMutableArray *valid=[NSMutableArray new];for(id row in list)if([row isKindOfClass:NSDictionary.class]){id ms=[row[@"mainSong"]isKindOfClass:NSDictionary.class]?row[@"mainSong"]:nil;if(ms){id vid=row[@"id"];if(vid){NSMutableDictionary *m=[ms mutableCopy];m[@"voiceId"]=vid;ms=m;}[valid addObject:ms];}}NSArray *ordered=[[valid reverseObjectEnumerator]allObjects];s.results=ordered;{NSData *plData=[NSJSONSerialization dataWithJSONObject:ordered options:0 error:nil];if(plData)[NSUserDefaults.standardUserDefaults setObject:plData forKey:@"TurboMusicPlaylistV1"];}s.pageMode.selectedSegmentIndex=1;[s pageModeChanged];s.navigationItem.prompt=err?:[NSString stringWithFormat:@"%lu 集 · 向下选择节目",(unsigned long)s.results.count];[s.tableView reloadData];if(s.results.count)[s.tableView scrollToRowAtIndexPath:[NSIndexPath indexPathForRow:0 inSection:0]atScrollPosition:UITableViewScrollPositionTop animated:YES];}];}
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section{return _pageMode.selectedSegmentIndex==1?_results.count:0;}
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)ip{UITableViewCell *c=[tableView dequeueReusableCellWithIdentifier:@"song"]?:[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:@"song"];id s=_results[ip.row];c.textLabel.text=[s[@"name"]isKindOfClass:NSString.class]?s[@"name"]:@"歌曲";NSArray *ar=[s[@"ar"]isKindOfClass:NSArray.class]?s[@"ar"]:@[];NSMutableArray *names=[NSMutableArray new];for(id a in ar)if([a[@"name"]isKindOfClass:NSString.class])[names addObject:a[@"name"]];c.detailTextLabel.text=[names componentsJoinedByString:@" / "];c.imageView.image=[UIImage systemImageNamed:@"music.note"];c.imageView.tintColor=TIOAccent();c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;c.backgroundColor=UIColor.secondarySystemGroupedBackgroundColor;return c;}
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)ip{return 64;}
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)ip{[tableView deselectRowAtIndexPath:ip animated:YES];[TMPlayer.shared playSong:_results[ip.row] queue:_results];self.pageMode.selectedSegmentIndex=0;[self pageModeChanged];[tableView setContentOffset:CGPointMake(0,-tableView.adjustedContentInset.top) animated:YES];}
@end
UIViewController *TMMusicController(void){return [[TMMusicPanel alloc]initWithStyle:UITableViewStyleInsetGrouped];}
